export enum GenderType {
  MALE = "MALE",
  FEMALE = "FEMALE",
}

export enum AccountType {
  GOOGLE = 'GOOGLE',
  LOCAL = 'LOCAL'
}

export enum ExamRegistrationStatusType {
  REGISTERED = 'REGISTERED',
  BLOCKED = 'BLOCKED',
  BANNED = 'BANNED',
  CANCELLED = 'CANCELLED'
}

export enum FraudLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH'
}


export enum FraudType {
  FACE_MISMATCH = 'FACE_MISMATCH',
  MULTIPLE_FACES_DETECTED = 'MULTIPLE_FACES_DETECTED',
  NO_FACE_DETECTED = 'NO_FACE_DETECTED',
  TAB_SWITCHING = 'TAB_SWITCHING',
  WINDOW_BLUR = 'WINDOW_BLUR',
  IP_CHANGED = 'IP_CHANGED',
  NETWORK_DISRUPTION = 'NETWORK_DISRUPTION'
}

export enum ResultGradingRole {
  REVIEWER = 'REVIEWER',
  FINAL_APPROVER = 'FINAL_APPROVER'
}

export enum QuestionType {
  SINGLE_CHOICE = 'SINGLE_CHOICE',
  TRUE_FALSE = 'TRUE_FALSE',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  FILL_IN_THE_BLANK = 'FILL_IN_THE_BLANK',
  ESSAY = 'ESSAY'
}

export enum ProctoringHandleType {
  WARNING = 'WARNING',
  STOP_FOR_SESSION_TRANSFER = 'STOP_FOR_SESSION_TRANSFER',
  REPRIMAND = 'REPRIMAND',
  SUSPENSION = 'SUSPENSION'
}

export enum RoleType {
  ADMIN = 'ADMIN',
  TEACHER = 'TEACHER',
  STUDENT = 'STUDENT'
}